require(sqldf)
require(data.table)
#power_data <- read.csv.sql("household_power_consumption.txt", sep=";", header=TRUE, sql= "select * from file where Date ='1/2/2007' or Date='2/2/2007'")
#power_data <- fread("household_power_consumption.txt", header=TRUE, sep=";", na.strings="?")
power_data <- read.csv("household_power_consumption.txt", header=TRUE, sep=";", na.strings="?")
power_data <- na.omit(power_data)
power_data <- power_data[power_data$Date %in% c("1/2/2007", "2/2/2007"),]
power_data$Date <- strptime(paste(power_data$Date,power_data$Time), "%d/%m/%Y %H:%M:%S")
png("plot3.png", width=480, height=480)
plot(power_data[,1], power_data[,7], type="l", ylab="Energy sub metering", xlab="")
lines(power_data[,1], power_data[,8], type="l", xlab="", col="red")
lines(power_data[,1], power_data[,9], type="l", xlab="", col="blue")
legend("topright", col=c("black", "red", "blue"), legend=c("sub_metering_1", "sub_metering_2", "sub_metering_3"), lty=1)
dev.off()